version: '1.0'

services:
  database:
      container_name: nest_db
      image: postgres:latest
      environment:
        - POSTGRES_DB=apinestjs
        - POSTGRES_USER=docker
        - POSTGRES_PASSWORD=docker
      ports:
      - 5432:5432